-- MySQL Script generated by MySQL Workbench
-- Wed Nov 15 16:19:36 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Table `melis_cms_domain_robots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `melis_cms_domain_robots` ;

CREATE TABLE IF NOT EXISTS `melis_cms_domain_robots` (
  `robot_id` INT NOT NULL AUTO_INCREMENT,
  `robot_site_domain` VARCHAR(200) NULL,
  `robot_text` TEXT NULL,
  PRIMARY KEY (`robot_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
