<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';

?>
<div<?= $id; ?>  class="tab-pane container-level-a" data-melisKey='<?= $this->melisKey; ?>'>
    <?php
    if(!$this->noAccess)
    {
        if(!empty($this->zoneconfig['interface'])) {
            foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                echo $this->$keyConfig;
            }
        }
    }
    else
    {
        echo '<h4>NO ACCESS</h4>';
    }

    ?>
</div>
 